import { mkdir, writeFile } from "node:fs/promises";
import * as path from "node:path";

import { createContributionPerfectPairData, type ContributionPerfectPairDataByLanguage } from "../src/contributions/perfect-pair-data";
import { languageDatasets } from "../src/languages";

const outputDir = path.join(import.meta.dir, "..", "src", "generated");
const outputPath = path.join(outputDir, "contribution-perfect-pairs.ts");

const data = Object.fromEntries(
  languageDatasets.map((dataset) => [dataset.id, createContributionPerfectPairData(dataset)]),
) satisfies ContributionPerfectPairDataByLanguage;

const contents = `// This file is generated by scripts/generate-contribution-perfect-pairs.ts. Do not edit manually.
import type { ContributionPerfectPairDataByLanguage } from "../contributions/perfect-pair-data";

export const contributionPerfectPairDataByLanguage = ${JSON.stringify(data, null, 2)} as const satisfies ContributionPerfectPairDataByLanguage;
`;

await mkdir(outputDir, { recursive: true });
await writeFile(outputPath, contents);

console.log(`Generated ${path.relative(path.join(import.meta.dir, ".."), outputPath)}`);
